### ISSUE TITLE
Error load main page

### ISSUE THREAD

**Issue by Wchoteheey** [Open-Games-Community/Telara-ZnoteAAC-Layout#1]
Hello,

I started to setup my webpage but I have following error:

`string(64) "SELECT COUNT(`id`) AS `count` from `players` WHERE `online` = 1;"`

Of course I imported tfs and znote schema.

**Comment by Alexv45** [comment]
> Hello,
> 
> I started to setup my webpage but I have following error:
> 
> `string(64) "SELECT COUNT(`id`) AS `count`from`players`WHERE`online` = 1;"`
> 
> Of course I imported tfs and znote schema.

Hello dear,
What version of TFS are you using ?
Since all layouts has been tested for the last version of TFS 1.3, coupling it with Otservbr 12.64.

It was not tested for other TFS Version, but it will works also, just some codes for example like Powergamers it will maybe not work until you import correct lua functions from Znote , see lua/ and version of TFS from znote folder.

**Comment by Wchoteheey** [comment]
Hello, 

it's TFS 1.4 (https://github.com/otland/forgottenserver/tree/1.4) I don't see any TFS 1.3 version. Probably was rename ? Of cource I had only one choice on Znote Acc to use `$config['ServerEngine'] = 'TFS_03';`
I thing that should be compatible, but doesn't work.
Can you help me ? It seems like query looking online players all the time right?

**Comment by Alexv45** [comment]
Website using: [Telara ZnoteAAC](https://github.com/Open-Games-Community/Telara-ZnoteAAC-Layout)
TFS Used: TFS_03
Server: [Global by NVSO 8.60](https://opengamescommunity.com/index.php?resources/global-8-60-by-nvso-real-map.4/)

Is working well, and online players also.
From TFS 1.3 to TFS 1.4 maybe some codes changes, but not from website i think.
Then Maybe try to use TFS_10 instead of TFS_03 ?

![2](https://user-images.githubusercontent.com/89811188/144584189-79e593c5-8879-4085-88b9-bec4aa216939.png)
